runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  script: main.app

- url: /images
  static_dir: images

- url: /upload
  script: main.app